/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatSpacegrayIJTheme;
import javax.swing.UIManager;

/**
 *
 * @author YanesH
 */
public class PaginaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PaginaPrincipal
     */
    public PaginaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpanelBg = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        JtpFunciones = new javax.swing.JTabbedPane();
        JfunInventario = new javax.swing.JPanel();
        JbtnCrearArt = new javax.swing.JButton();
        JfunSocioNegocio = new javax.swing.JPanel();
        JbtnCrearSocio = new javax.swing.JButton();
        JfunCliente = new javax.swing.JPanel();
        JbtnFactVentas = new javax.swing.JButton();
        JfunProveedor = new javax.swing.JPanel();
        JbtnFactClientes = new javax.swing.JButton();
        JpaneAyuda = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jMenuBar = new javax.swing.JMenuBar();
        JmenuArchivo = new javax.swing.JMenu();
        JmenuCerrarSesion = new javax.swing.JMenuItem();
        JmenuSalir = new javax.swing.JMenuItem();
        JmenuModulo = new javax.swing.JMenu();
        JmenuInventario = new javax.swing.JMenu();
        JmenuCrearArt = new javax.swing.JMenuItem();
        JmenuSocioNegocio = new javax.swing.JMenu();
        JmenuCrearSocioNegocio = new javax.swing.JMenuItem();
        JmenuCliente = new javax.swing.JMenu();
        JmenuFactDeudor = new javax.swing.JMenuItem();
        JmenuProveedor = new javax.swing.JMenu();
        JmenuFactAcreedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setUndecorated(true);

        JpanelBg.setBackground(new java.awt.Color(255, 255, 255));
        JpanelBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        JpanelBg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 832, 10));

        JtpFunciones.setBackground(new java.awt.Color(255, 255, 255));
        JtpFunciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Funciones"));
        JtpFunciones.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        JtpFunciones.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        JfunInventario.setBackground(new java.awt.Color(255, 255, 255));
        JfunInventario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JbtnCrearArt.setBackground(new java.awt.Color(51, 153, 255));
        JbtnCrearArt.setForeground(new java.awt.Color(255, 255, 255));
        JbtnCrearArt.setText("Crear Articulos");

        javax.swing.GroupLayout JfunInventarioLayout = new javax.swing.GroupLayout(JfunInventario);
        JfunInventario.setLayout(JfunInventarioLayout);
        JfunInventarioLayout.setHorizontalGroup(
            JfunInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JfunInventarioLayout.createSequentialGroup()
                .addComponent(JbtnCrearArt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
        JfunInventarioLayout.setVerticalGroup(
            JfunInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JfunInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JbtnCrearArt)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        JtpFunciones.addTab("Inventario", JfunInventario);

        JfunSocioNegocio.setBackground(new java.awt.Color(255, 255, 255));
        JfunSocioNegocio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JbtnCrearSocio.setBackground(new java.awt.Color(51, 153, 255));
        JbtnCrearSocio.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        JbtnCrearSocio.setForeground(new java.awt.Color(255, 255, 255));
        JbtnCrearSocio.setText("Crear socio de negocio");
        JbtnCrearSocio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        javax.swing.GroupLayout JfunSocioNegocioLayout = new javax.swing.GroupLayout(JfunSocioNegocio);
        JfunSocioNegocio.setLayout(JfunSocioNegocioLayout);
        JfunSocioNegocioLayout.setHorizontalGroup(
            JfunSocioNegocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JfunSocioNegocioLayout.createSequentialGroup()
                .addComponent(JbtnCrearSocio, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
        JfunSocioNegocioLayout.setVerticalGroup(
            JfunSocioNegocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JfunSocioNegocioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JbtnCrearSocio)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        JtpFunciones.addTab("Socio de negocio", JfunSocioNegocio);

        JfunCliente.setBackground(new java.awt.Color(255, 255, 255));
        JfunCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JbtnFactVentas.setBackground(new java.awt.Color(51, 153, 255));
        JbtnFactVentas.setForeground(new java.awt.Color(255, 255, 255));
        JbtnFactVentas.setText("Factura de ventas");

        javax.swing.GroupLayout JfunClienteLayout = new javax.swing.GroupLayout(JfunCliente);
        JfunCliente.setLayout(JfunClienteLayout);
        JfunClienteLayout.setHorizontalGroup(
            JfunClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JfunClienteLayout.createSequentialGroup()
                .addComponent(JbtnFactVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
        JfunClienteLayout.setVerticalGroup(
            JfunClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JfunClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JbtnFactVentas)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        JtpFunciones.addTab("Ventas - Clientes", JfunCliente);

        JfunProveedor.setBackground(new java.awt.Color(255, 255, 255));
        JfunProveedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JbtnFactClientes.setBackground(new java.awt.Color(51, 153, 255));
        JbtnFactClientes.setForeground(new java.awt.Color(255, 255, 255));
        JbtnFactClientes.setText("Factura de compras");

        javax.swing.GroupLayout JfunProveedorLayout = new javax.swing.GroupLayout(JfunProveedor);
        JfunProveedor.setLayout(JfunProveedorLayout);
        JfunProveedorLayout.setHorizontalGroup(
            JfunProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JfunProveedorLayout.createSequentialGroup()
                .addComponent(JbtnFactClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
        JfunProveedorLayout.setVerticalGroup(
            JfunProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JfunProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JbtnFactClientes)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        JtpFunciones.addTab("Compras - Proveedores", JfunProveedor);

        JpanelBg.add(JtpFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 330, 320));

        JpaneAyuda.setBackground(new java.awt.Color(255, 255, 255));
        JpaneAyuda.setBorder(javax.swing.BorderFactory.createTitledBorder("Ayuda"));

        javax.swing.GroupLayout JpaneAyudaLayout = new javax.swing.GroupLayout(JpaneAyuda);
        JpaneAyuda.setLayout(JpaneAyudaLayout);
        JpaneAyudaLayout.setHorizontalGroup(
            JpaneAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        JpaneAyudaLayout.setVerticalGroup(
            JpaneAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        JpanelBg.add(JpaneAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 260, 300));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);
        JpanelBg.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 30));

        JmenuArchivo.setText("Archivo");

        JmenuCerrarSesion.setText("Cerrar Sesion");
        JmenuArchivo.add(JmenuCerrarSesion);

        JmenuSalir.setText("Salir");
        JmenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmenuSalirActionPerformed(evt);
            }
        });
        JmenuArchivo.add(JmenuSalir);

        jMenuBar.add(JmenuArchivo);

        JmenuModulo.setText("Modulos");
        JmenuModulo.setFocusPainted(true);

        JmenuInventario.setText("Inventario");

        JmenuCrearArt.setText("Crear Articulos");
        JmenuInventario.add(JmenuCrearArt);

        JmenuModulo.add(JmenuInventario);

        JmenuSocioNegocio.setText("Socio de Negocio ");

        JmenuCrearSocioNegocio.setText("Crear Socio de Negocio");
        JmenuSocioNegocio.add(JmenuCrearSocioNegocio);

        JmenuModulo.add(JmenuSocioNegocio);

        JmenuCliente.setText("Ventas - Clientes");

        JmenuFactDeudor.setText("Factura de Deudores");
        JmenuCliente.add(JmenuFactDeudor);

        JmenuModulo.add(JmenuCliente);

        JmenuProveedor.setText("Compras - Proveedores");

        JmenuFactAcreedor.setText("Factura de Compras");
        JmenuProveedor.add(JmenuFactAcreedor);

        JmenuModulo.add(JmenuProveedor);

        jMenuBar.add(JmenuModulo);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpanelBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpanelBg, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JmenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmenuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JmenuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    FlatCyanLightIJTheme.setup();
                }catch(Exception e){
                    e.printStackTrace();
                }
                new PaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnCrearArt;
    private javax.swing.JButton JbtnCrearSocio;
    private javax.swing.JButton JbtnFactClientes;
    private javax.swing.JButton JbtnFactVentas;
    private javax.swing.JPanel JfunCliente;
    private javax.swing.JPanel JfunInventario;
    private javax.swing.JPanel JfunProveedor;
    private javax.swing.JPanel JfunSocioNegocio;
    private javax.swing.JMenu JmenuArchivo;
    private javax.swing.JMenuItem JmenuCerrarSesion;
    private javax.swing.JMenu JmenuCliente;
    private javax.swing.JMenuItem JmenuCrearArt;
    private javax.swing.JMenuItem JmenuCrearSocioNegocio;
    private javax.swing.JMenuItem JmenuFactAcreedor;
    private javax.swing.JMenuItem JmenuFactDeudor;
    private javax.swing.JMenu JmenuInventario;
    private javax.swing.JMenu JmenuModulo;
    private javax.swing.JMenu JmenuProveedor;
    private javax.swing.JMenuItem JmenuSalir;
    private javax.swing.JMenu JmenuSocioNegocio;
    private javax.swing.JPanel JpaneAyuda;
    private javax.swing.JPanel JpanelBg;
    private javax.swing.JTabbedPane JtpFunciones;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
