
package proyecto4tosemestre;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.UIManager;


public class Login extends javax.swing.JFrame {

    private ImageIcon img;
    private Icon icon;
    
    
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.redimensionarImagen(this.JetiImg, "src/Imagenes/ic_user_1.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        JpanelContenedor = new javax.swing.JPanel();
        JetiClave = new javax.swing.JLabel();
        JetiID = new javax.swing.JLabel();
        JtxtPass = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        JetiImg = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        JetiNombreSoftware = new javax.swing.JLabel();
        JbtnSalir = new javax.swing.JButton();
        JbtnIngresar = new javax.swing.JButton();
        JtxtID = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        JpanelContenedor.setBackground(java.awt.Color.white);
        JpanelContenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JpanelContenedor.setToolTipText("Sys");
        JpanelContenedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JpanelContenedor.setName("System ERP"); // NOI18N
        JpanelContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JetiClave.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        JetiClave.setText("Clave de Acceso");
        JpanelContenedor.add(JetiClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        JetiID.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        JetiID.setText("ID Usuario");
        JpanelContenedor.add(JetiID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        JtxtPass.setForeground(new java.awt.Color(204, 204, 204));
        JtxtPass.setText("Ingrese ID de Usuario");
        JtxtPass.setBorder(null);
        JtxtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtxtPassMouseClicked(evt);
            }
        });
        JtxtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtPassActionPerformed(evt);
            }
        });
        JpanelContenedor.add(JtxtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 170, 20));
        JpanelContenedor.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, -1));
        JpanelContenedor.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 170, -1));
        JpanelContenedor.add(JetiImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 110, 100));
        JpanelContenedor.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 440, -1));

        JetiNombreSoftware.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 18)); // NOI18N
        JetiNombreSoftware.setText("SYSTEM ERP");
        JpanelContenedor.add(JetiNombreSoftware, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        JbtnSalir.setBackground(new java.awt.Color(153, 153, 153));
        JbtnSalir.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        JbtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        JbtnSalir.setText("Salir");
        JbtnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        JbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnSalirActionPerformed(evt);
            }
        });
        JpanelContenedor.add(JbtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 80, 30));

        JbtnIngresar.setBackground(new java.awt.Color(51, 153, 255));
        JbtnIngresar.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        JbtnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        JbtnIngresar.setText("Ingresar");
        JbtnIngresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        JbtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnIngresarActionPerformed(evt);
            }
        });
        JpanelContenedor.add(JbtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, 30));

        JtxtID.setForeground(new java.awt.Color(204, 204, 204));
        JtxtID.setText("Ingrese ID de Usuario");
        JtxtID.setBorder(null);
        JtxtID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtxtIDMouseClicked(evt);
            }
        });
        JtxtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtIDActionPerformed(evt);
            }
        });
        JpanelContenedor.add(JtxtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 170, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtxtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtPassActionPerformed

    private void JtxtPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtxtPassMouseClicked
   
    }//GEN-LAST:event_JtxtPassMouseClicked

    private void JbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JbtnSalirActionPerformed

    private void JbtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnIngresarActionPerformed

    private void JtxtIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtxtIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtIDMouseClicked

    private void JtxtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Dark Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new FlatLightLaf());
                }catch(Exception e){
                    e.printStackTrace();
                }
                new Login().setVisible(true);
            }
        });
    }
    
    private void redimensionarImagen (JLabel lbl,String ruta){
        this.img = new ImageIcon(ruta);
        this.icon = new ImageIcon(this.img.getImage().getScaledInstance(
                lbl.getWidth(), 
                lbl.getHeight(), 
                Image.SCALE_SMOOTH));
        lbl.setIcon(icon);
        this.repaint();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JbtnIngresar;
    public javax.swing.JButton JbtnSalir;
    private javax.swing.JLabel JetiClave;
    private javax.swing.JLabel JetiID;
    private javax.swing.JLabel JetiImg;
    private javax.swing.JLabel JetiNombreSoftware;
    private javax.swing.JPanel JpanelContenedor;
    public javax.swing.JTextField JtxtID;
    public javax.swing.JTextField JtxtPass;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
